name: setup-python-test

on:
  workflow_dispatch:
  push:

jobs:
  python-action-test:
    runs-on: ubuntu-20.04-ppc64le
    strategy:
      matrix:
        arch: [ ppc64le ]
    steps:
      - uses: actions/checkout@v3
      - if: ${{ matrix.arch == 'ppc64le' }}
        uses: deadsnakes/action@v3.1.0
        with:
          python-version: "3.11"
      - run: |
          python --version
          which python
          python my_script.py
