name: setup-python-test

on:
  workflow_dispatch:
  push:

jobs:
  python-action-test:
    runs-on: ubuntu-20.04-ppc64le
    steps:
      - uses: actions/checkout@v3
      - uses: shahidhs-ibm/setup-python@ppc64le
        with:
          python-version: '3.10'
      - run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip
          sudo ln -s /usr/bin/python3 /usr/bin/python
          python3 --version
          python --version
          python3 my_script.py
          python -m ensurepip
          python -m pip install --ignore-installed pip --disable-pip-version-check --no-warn-script-location
