name: setup-python-test

on:
  workflow_dispatch:
  push:

jobs:
  python-action-test:
    runs-on: ubuntu-20.04-ppc64le
    steps:
      - uses: actions/checkout@v3
      - uses: shahidhs-ibm/setup-python@ppc64le
        with:
          python-version: '3.10'
      - run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          if [ ! -f /usr/bin/python ]; then
            sudo ln -s /usr/bin/python3 /usr/bin/python
          fi
          python3 --version
          python --version
          python3 my_script.py
          pip3 --version
