name: setup-python-test

on:
  workflow_dispatch:
  push:

jobs:
  python-action-test:
    runs-on: ubuntu-20.04-ppc64le
    steps:
      - uses: actions/checkout@v3
      - uses: shahidhs-ibm/setup-python@ppc64le
        with:
          python-version: '3.10'
      - run: |
          apt-get install python3
          python3 --version
          python --version
          python my_script.py
